<?php

namespace IrinBundle\Repository;

use Doctrine\ORM\EntityRepository;
use IrinBundle\Contracts\Repository\KepribadianInterface;
use IrinBundle\Entity\Kepribadian;

/**
 * KepribadianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KepribadianRepository extends EntityRepository implements KepribadianInterface
{
    /**
     * @param $id
     * @return Kepribadian
     */
    public function findById($id)
    {
        return $this->find($id);
    }

    /**
     * @param $userId
     * @return Kepribadian
     */
    public function findByUserId($userId)
    {
        return $this->findOneBy(['userId'=>$userId]);
    }
}
