irin_user:
      resource: "@IrinBundle/Resources/config/routing/routing_user.yml"
      prefix: /user

irin_admin:
      resource: "@IrinBundle/Resources/config/routing/routing_admin.yml"
      prefix: /admin

irin_index:
      path: /
      defaults:
        _controller: IrinBundle:Security:loginCheck

irin_register:
      path: /register
      defaults: { _controller: IrinBundle:User:create }

irin_forgot:
      path: /forgot-password
      defaults: { _controller: IrinBundle:User:forgetPassword }

irin_reset:
      path: /reset/{token}
      defaults: { _controller: IrinBundle:User:reset }

irin_logout:
      path: /logout

